version: "3.6"
services:
  postgres:
    image: postgres:15
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    env_file:
      - ../../.env
    ports:
      - "5432:5432"
    networks:
      - fambot-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 120s

networks:
  fambot-network:
    driver: bridge
