version: "3.6"
services:
  discord-bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ../../.env
    networks:
      - fambot-network

networks:
  fambot-network:
    driver: bridge
